### ISSUE TITLE
Some Features

### ISSUE THREAD

**Issue by thewebsiteclue** [draeton/stitches#8] opened 2013-02-14 21:15 UTC
1-adding arrangement ability to items
2-style sheet and image download in zip or on click
3-test the style and sprite in same page to make sure the user is pretty satisfied with it.
thanks for your hard work bb

**Comment by draeton** [comment] 2013-02-27 18:59
I like all of these features:
1 - Rearranging I would like to handle through drag & drop.
2 - The zip download is interesting... there are compression algorithms in JS available so I think I'll check those out
3 - Can you elaborate on this one?

**Comment by InsidiousForce** [comment] 2013-03-08 19:55
I agree with 1. How are these currently arranged? If I name the images a certain way are they arranged by filename? Or? would be good to have some way to predict how these end up in the final layout. If I couple that with below it is suddenly very useful:

I'd also like to see a way to specify a width/height for the sheet, like 3 wide or 4 tall and have the sheet flow in that way. Sometimes you set up a sheet with say different character walking cycles, and they all have to have 12 frames. So to specify a width of 12 would be useful here.

thanks for the work on this.

**Comment by draeton** [comment] 2013-03-09 03:14
Sprites are sorted by area (descending), then name. This was originally implemented as a way to optimize the sprite placement algorithm to use the least amount of space. Given the way this is being used by designers, I have been getting feedback that this is sub-optimal because sprite sheets typically contain similarly-sized images. So, I'll switch that to just sorting on name.

Specifying rows and columns are one way of going about things--if you're still interested after what I have to say, feel free to open an issue request... I'm planning on implementing groups. You will be able to select multiple sprites and click a button to group them. Groups can have their own layout applied (i.e. compact, horizontal, vertical). So you'll be able to have a horizontal group of sprites, and then use the vertical canvas layout to have rows. Something to think about...

@thewebsiteclue - There doesn't seem to be a consistent way to download a JS-generated zip file without using Flash. I want to avoid using that here, so I'm going to close this issue. I will be opening an issue for the sprite arranging.

**Closed as completed by draeton** 2013-03-09 03:14 UTC

**Comment by InsidiousForce** [comment] 2013-03-09 06:11
groups do seem like they would adequately work in the situation that I laid out.
